### ISSUE TITLE
(0.7.9) Riot Armor has no non-shield variant 

### ISSUE THREAD

**Issue by Anxoczt** [8mono/XComFilesArsenalAdditions#1]
![obrázek_2022-03-15_090543](https://user-images.githubusercontent.com/50877085/158333011-67ff82a4-cd68-4b36-a8ec-b33e0e8f8b1b.png)

I guess this is a oversight, because on the in game ufopedia there is the standard armor without a shield. 
![image](https://user-images.githubusercontent.com/50877085/158333196-6da47e2f-f81d-412f-bcd5-07b9044fac8c.png)

**Comment by 8mono** [comment]
I can see riot armor just fine on my end, I don't think I've changed any of the code for it recently. Is your agent human? any other transformations?
![image](https://user-images.githubusercontent.com/55917502/158409049-b5f213dc-15da-4d60-9514-d119430b9262.png)

**Comment by 8mono** [comment]
Found it! I accidentally set the required research to be STR_NIGHTOPS on this too, instead of just flashlights, thanks! I'll rectify that in a bit
