### ISSUE TITLE
Crash on missing UFOpaedia Article Mini Mortar

### ISSUE THREAD

**Issue by Oriskana** [8mono/XComFilesArsenalAdditions#2]
Hey there, got a crash using latest version (to be precise Master from 26/03/2022), more in the screenshot:
![Gas shell](https://user-images.githubusercontent.com/40295921/160274869-9e496a3d-5916-48af-a2af-1bbc01780611.png)

Cheers mate.

**Comment by 8mono** [comment]
Should be fixed now, thanks!
![image](https://user-images.githubusercontent.com/55917502/160288978-ee10d1bc-5ab6-4588-844b-72539f46789c.png)
