### ISSUE TITLE
Not compatible with Xcom Xfiles 2.4

### ISSUE THREAD

**Issue by Oriskana** [8mono/XComFilesArsenalAdditions#3]
Hey there,

updated Xcom Xfiles to latest version 2.4 (07/04/2022).

It doesn't load with your submod.

Cheers mate.

[openxcom.log](https://github.com/8mono/XComFilesArsenalAdditions/files/8443592/openxcom.log)

**Comment by 8mono** [comment]
Thank you! this was a bit hard to find, the armor for Synthsuit_Underwater was being referenced in scripts for the tags, but it no longer exists. It has been removed and issue resolved

![image](https://user-images.githubusercontent.com/55917502/162364131-32e44321-6343-430a-ac6a-30d467040c2f.png)
